#!/bin/bash

set -e

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
. "$SCRIPT_DIR/common.sh"

mkdir -p "$GAME_DIR"

correct_size_found=
db_rebuild_required=

while read url; do
    file=$(basename "$url")
    if [[ -e "$GAME_DIR/$file" ]]; then
        if [[ -n "$correct_size_found" ]]; then
            # we don't bother checking the new size of allgames201409.tgz
            # (and older) if the size of allgames201410.tgz was already correct
            continue
        fi

        old_size=$(stat -c %s "$GAME_DIR/$file")
        new_size=$(wget --spider "$url" 2>&1 |
                   awk '$1 == "Length:" { print $2 }')
        if [[ $old_size = $new_size ]]; then
            correct_size_found=1
            continue
        else
            rm -f "$GAME_DIR/$file"
        fi
    fi
    wget --directory-prefix "$GAME_DIR" "$url"
    db_rebuild_required=1
done < <(lynx -dump -listonly -nonumbers \
          http://arimaa.com/arimaa/download/gameData |
         egrep '/allgames[0-9]+\.tgz' | tac)

if [[ -n "$db_rebuild_required" ]]; then
    >"$GAME_DB"
    sed_command=  # noop
    for archive in "$GAME_DIR"/*.tgz; do
        tar xf "$archive" -O | sed "$sed_command" >>"$GAME_DB"
        sed_command=1d  # remove header
    done
fi
