#!/bin/bash

GAME_FILE=allgames201404.txt

head -1 $GAME_FILE
awk -F'\t' '
  $10 >= 1800 &&  # wrating
  $11 >= 1800 &&  # brating
  $14 == "h"  &&  # wtype
  $15 == "h"  &&  # btype
  $24 >= 10       # plycount
' $GAME_FILE
