#!/bin/bash

set -e

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
. "$SCRIPT_DIR/common.sh"

head -1 "$GAME_DB"
awk -F'\t' '
  $10 >= 1800 &&  # wrating
  $11 >= 1800 &&  # brating
  $14 == "h"  &&  # wtype
  $15 == "h"  &&  # btype
  $24 >= 10   &&  # plycount
  $26 == 1        # rated
' "$GAME_DB"
