#!/usr/bin/ruby

require 'getoptlong'
require_relative 'lib/movelist'

##### Argument parsing

def usage()
  abort "Usage: #$0 [-n|--normalize] [-s|--skip_duplicates]"
end

options = {}
GetoptLong.new(
  ['--help', '-h', GetoptLong::NO_ARGUMENT],
  ['--normalize', '-n', GetoptLong::NO_ARGUMENT],
  ['--skip_duplicates', '-s', GetoptLong::NO_ARGUMENT]
).each do |name, value|
  options[name.sub(/^--/, '').to_sym] = value
end

if options['help'] or not ARGV.empty?
  usage
end

##### Main program

GAMEID_COLUMN = 0  # i.e. 1st field
MOVELIST_COLUMN = 27  # i.e. 28th field

stream = if STDIN.tty?
           GAME_DB=%x{. #{File.dirname(__FILE__)}/common.sh
                      echo $GAME_DB}.chomp
           open(GAME_DB)
         else
           STDIN
         end
stream.each_with_index do |line, index|
  next if index == 0  # header

  fields = line.force_encoding('BINARY').split("\t")
  MoveList.new(fields[MOVELIST_COLUMN]).each(options) do |fen|
    puts "#{fields[GAMEID_COLUMN]}\t#{fen}"
  end
end
