######################################################################
# Automatically generated by qmake (3.0) Wed Apr 1 00:03:38 2015
######################################################################

CONFIG += c++11 testcase
QT += testlib

TEMPLATE = app
TARGET = testrunner
INCLUDEPATH += .

DEFINES += QT_NO_CAST_FROM_ASCII \
           QT_NO_CAST_TO_ASCII

HEADERS += movelist.h testmovelist.h
SOURCES += testmovelist.cpp
