name: Ruby CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version: ["2.7", "3.1", "3.3"]

    steps:
    - uses: actions/checkout@v4
    - name: Set up Ruby ${{ matrix.ruby-version }}
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby-version }}
    - name: rubocop
      run: |
        gem install rubocop
        rubocop normalized-setups positions lib/*.rb
    - name: Test
      run: |
        ./lib/test_movelist.rb
